#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  3 13:10:49 2019

@author: sarafergus
"""
from WHR_EDA import get_var
from WHR_EDA import info_dict
import matplotlib.pyplot as plt
import statistics
    
##############################################################################

def histogram(information, title, bins):
    '''Make histogram of military measurements'''
    fig,ax = plt.subplots()
    textstr = 'Mean: ' + str(round(statistics.mean(information),2)) + '%\n SD: ' + str(round(statistics.stdev(information),4))
    props = dict(boxstyle='round', facecolor='white', alpha=1)
    ax.text(0.67, 0.95, textstr, transform=ax.transAxes, fontsize=14,
    verticalalignment='top', bbox=props)
    plt.hist(information, bins = bins)
    plt.title(title)
    plt.xlabel('Percent')
    plt.ylabel('Count')
    plt.show()

def cdf(information, title, marks, vals):
    '''make CDF of military measurements, marking countries of interest'''
    x_cdf = sorted(information)
    N = len(x_cdf)
    y_cdf = [ (N-1.0-i)/N for i in range(N) ]
    plt.title(title)
    plt.plot(x_cdf, y_cdf, '.-')
    for i in range(len(vals)):
        plt.plot([vals[i], vals[i]], [0,1], '--', label=marks[i]) 
    plt.xlabel("Spending Percent$(x)$");plt.ylabel("$P(X>x)$"); plt.legend();
    plt.show()
    
##############################################################################
    
marks = ['United States', 'Finland', 'Central African Republic', 'Paraguay', 'Turkey', 'Taiwan']
    
milt_gov, _ = get_var(info_dict, 'Percent Military(of Gov)', [])
milt_gov = [x for x in milt_gov if x != 0]
milt_gdp, _ = get_var(info_dict, 'Percent Military(of GDP)', [])
milt_gdp = [x for x in milt_gdp if x != 0]

vals = [info_dict[item]['Percent Military(of Gov)'] for item in marks if info_dict[item]['Percent Military(of Gov)']!= 0]  
vals2 = [info_dict[item]['Percent Military(of GDP)'] for item in marks if info_dict[item]['Percent Military(of GDP)']!= 0]  

histogram(milt_gov, 'Military Spending as a Percent of Government Spending', 20)
histogram(milt_gdp, 'Military Spending as a Percent of GDP', 20)

cdf(milt_gov, "Military Spending by Percent of Government Spending", marks, vals)
cdf(milt_gdp, "Military Spending by Percent of GDP", marks, vals2)
